### ISSUE TITLE
Inconsistent behavior between server side apply and client side apply on type mismatch error handling

### ISSUE THREAD

**Issue by cici37** [kubernetes-sigs/structured-merge-diff#209]
There is inconsistent behavior between server side apply and client side apply on type mismatch error handling. In server side apply, type mismatch error will be caught during structural merge and stop proceeding to further validation.

For CRD example:
```
......
openAPIV3Schema:
        type: object
        properties:
          a:
            type: array
            items:
              type: string
            x-kubernetes-validations:
            - rule: self != []
          s:
            type: string
            x-kubernetes-validations:
            - rule: self != ""
          i:
            type: integer
            x-kubernetes-validations:
            - rule: self != 0
```
When try to create CR like:
```
apiVersion: example.com/v1
kind: Mismatch
metadata:
  name: string
a: "a"
s: 1
i: "a"
```
` kubectl apply --server-side -f cr_mismatch_string.yaml --validate=false` will return:
```
Error from server: failed to create typed patch object (default/string; example.com/v1, Kind=Mismatch): errors:
  .i: expected numeric (int or float), got string
  .s: expected string, got &value.valueUnstructured{Value:1}
  .a: expected list, got &{a}
```
While `kubectl apply -f cr_mismatch_string.yaml --validate=false` will return:
```
The Mismatch "string" is invalid: 
* s: Invalid value: "integer": s in body must be of type string: "integer"
* a: Invalid value: "string": a in body must be of type array: "string"
* i: Invalid value: "string": i in body must be of type integer: "string"
* a: Invalid value: "a": invalid data, expected []interface{} to match the provided schema with type=array evaluating rule: self != []
* i: Invalid value: "a": invalid data, expected int, got string evaluating rule: self != 0
* s: Invalid value: 1: invalid data, expected string, got int64 evaluating rule: self != ""
```
